# TD n°2 : NumPy

In [1]:
import numpy as np

### 1.

In [2]:
# Supposons que 'tableau' est notre tableau NumPy 2D
tableau = np.array([[1, 2], [3, 4]])

# Calcul de la moyenne sur chaque dimension
moyenne_colonnes = np.mean(tableau, axis=0)
moyenne_lignes = np.mean(tableau, axis=1)
print("moyenne par colonnes\t : ",moyenne_colonnes)
print("moyenne par lignes\t : ",moyenne_lignes)

moyenne par colonnes	 :  [2. 3.]
moyenne par lignes	 :  [1.5 3.5]


### 2.

In [3]:
# Supposons que 'tableaux' est une liste de trois tableaux NumPy 3x3
tableaux = [np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
            np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]),
            np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])]

# Calculs demandés
for tableau in tableaux:
    somme_cumulee = np.cumsum(tableau)
    somme_lignes = np.sum(tableau, axis=1)
    somme_colonnes = np.sum(tableau, axis=0)
    
print("somme cumulée\t\t : ",somme_cumulee)
print("somme par lignes\t : ",somme_lignes)
print("somme par colonnes\t : ",somme_colonnes)

somme cumulée		 :  [ 2  6 12 20 30 42 56 72 90]
somme par lignes	 :  [12 30 48]
somme par colonnes	 :  [24 30 36]


### 3.

In [4]:
# Supposons que 'tableau_2d' est notre tableau NumPy 2D à trier
tableau_2d = np.array([[2, 1], [4, 3]])
print("tableau 2d :\n",tableau_2d)
print("\n")

# Triage selon le premier axe
trie_premier_axe = np.sort(tableau_2d, axis=0)
print("trie premier axe :\n",trie_premier_axe,"\n")

# Triage selon le dernier axe
trie_dernier_axe = np.sort(tableau_2d, axis=-1)
print("trie dernier axe :\n",trie_dernier_axe,"\n")

# Triage du tableau aplati
tableau_aplati = tableau_2d.flatten()
trie_aplati = np.sort(tableau_aplati)
print("tableau aplati :\n",tableau_aplati,"\n")
print("trie aplati :\n",trie_aplati,"\n")

tableau 2d :
 [[2 1]
 [4 3]]


trie premier axe :
 [[2 1]
 [4 3]] 

trie dernier axe :
 [[1 2]
 [3 4]] 

tableau aplati :
 [2 1 4 3] 

trie aplati :
 [1 2 3 4] 



### 4. 

In [5]:
# Création d'un cube 5x5x5 rempli de 1
cube = np.ones((5, 5, 5))
print("Cube 5x5x5 de 1:\n", cube)

Cube 5x5x5 de 1:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 5. 

In [6]:
# Supposons que 'tableau_4x4' est notre tableau NumPy 4x4
tableau_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Extraction de la troisième colonne
troisieme_colonne = tableau_4x4[:, 2]
print("Troisième colonne:", troisieme_colonne)

Troisième colonne: [ 3  7 11 15]


### 6. 

In [7]:
# Extraction des éléments requis
premier_deuxieme_elements = tableau_4x4[:2, :2]
print("Premiers et deuxièmes éléments des deux premières lignes:\n", premier_deuxieme_elements)

Premiers et deuxièmes éléments des deux premières lignes:
 [[1 2]
 [5 6]]


### 7. 

In [8]:
# Extraction des éléments requis
troisieme_quatrieme_elements = tableau_4x4[:2, 2:]
print("Troisièmes et quatrièmes éléments des deux premières lignes:", troisieme_quatrieme_elements)

Troisièmes et quatrièmes éléments des deux premières lignes: [[3 4]
 [7 8]]


### 8.

In [9]:
# Création de la série aléatoire de 10 éléments
serie_aleatoire = np.random.rand(10)

# Partitionnement en 2 avec 5 éléments chacun
partition_1, partition_2 = np.array_split(serie_aleatoire, 2)

# Tri par ordre croissant
serie_triee = np.sort(serie_aleatoire)
print("Série triée:", serie_triee)

Série triée: [0.04820953 0.14555348 0.1981269  0.22437507 0.30676375 0.46606805
 0.59283953 0.67463487 0.79480983 0.8561755 ]


### 9.

In [10]:
# Création de la matrice d'entiers aléatoires
matrice_aleatoire = np.random.randint(0, 11, size=(3, 3))

# Tri de la matrice selon la deuxième colonne
matrice_triee = matrice_aleatoire[matrice_aleatoire[:, 1].argsort()]
print("Matrice triée selon la deuxième colonne:", matrice_triee)

Matrice triée selon la deuxième colonne: [[10  0  6]
 [ 6  3  9]
 [ 5  3  9]]


### 10.

In [11]:
# Création des matrices
matrice_a = np.random.rand(5, 3)
matrice_b = np.random.rand(3, 2)

# Produit matriciel
produit_matriciel = np.dot(matrice_a, matrice_b)
print("Produit matriciel:", produit_matriciel)


Produit matriciel: [[1.17687356 0.54790576]
 [0.53770819 0.18936551]
 [0.92373772 0.40271967]
 [1.60378069 0.85051321]
 [0.56960059 0.29568544]]


### 11.

In [12]:
# Création du tenseur x
x = np.arange(24).reshape((2, 3, 4))
print("Tenseur x:", x)

# Tenseur y
y = np.array([0, 1, 2, 3])

# Produit scalaire
produit_scalaire = np.tensordot(x, y, axes=([2], [0]))
print("Produit scalaire de x par y:", produit_scalaire)

Tenseur x: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Produit scalaire de x par y: [[ 14  38  62]
 [ 86 110 134]]
